@extends('layout')
@section('title','ยานพาหนะ / ขนส่ง')
@section('page-title','ยานพาหนะ / ขนส่ง')
@section('page-subtitle','ทะเบียนรถ การวิ่งรายวัน และประวัติซ่อม')
@section('content')
<div class="d-flex justify-content-end mb-3"><a class="btn btn-outline-primary" href="{{ route('fleet.report') }}">รายงานสรุปรถ</a></div>
<div class="row g-3">
<div class="col-lg-4"><div class="card"><div class="card-header">เพิ่มทะเบียนรถ</div><div class="card-body"><form method="POST" action="{{ route('fleet.vehicles.store') }}">@csrf
<select name="branch_id" class="form-select mb-2"><option value="">ไม่ระบุสาขา</option>@foreach($branches as $b)<option value="{{ $b->id }}">{{ $b->code }} · {{ $b->name_th }}</option>@endforeach</select>
<input name="code" class="form-control mb-2" placeholder="รหัสรถ" required><input name="registration" class="form-control mb-2" placeholder="ทะเบียนรถ" required><input name="vehicle_type" class="form-control mb-2" placeholder="ประเภทรถ" required><div class="row g-2"><div class="col"><input name="brand" class="form-control" placeholder="ยี่ห้อ"></div><div class="col"><input name="model" class="form-control" placeholder="รุ่น"></div></div><input name="current_odometer" type="number" min="0" class="form-control my-2" placeholder="เลขไมล์ปัจจุบัน" required><button class="btn btn-primary w-100">บันทึกรถ</button></form></div></div></div>
<div class="col-lg-8"><div class="card"><div class="card-header">ทะเบียนรถ</div><div class="table-responsive"><table class="table mb-0"><thead><tr><th>รหัส</th><th>ทะเบียน</th><th>ประเภทรถ</th><th>สาขา</th><th>เลขไมล์</th><th>สถานะ</th></tr></thead><tbody>@forelse($vehicles as $v)<tr><td>{{ $v->code }}</td><td><strong>{{ $v->registration }}</strong></td><td>{{ $v->vehicle_type }} {{ $v->brand }} {{ $v->model }}</td><td>{{ $v->branch?->name_th ?? '-' }}</td><td>{{ number_format($v->current_odometer) }}</td><td>{{ $v->status==='active'?'ใช้งาน':'พักใช้งาน' }}</td></tr>@empty<tr><td colspan="6" class="text-center">ยังไม่มีทะเบียนรถ</td></tr>@endforelse</tbody></table></div></div></div>
<div class="col-lg-6"><div class="card"><div class="card-header">บันทึกการวิ่ง</div><div class="card-body"><form method="POST" action="{{ route('fleet.trips.store') }}">@csrf<select name="vehicle_id" class="form-select mb-2" required><option value="">เลือกรถ</option>@foreach($vehicles as $v)<option value="{{ $v->id }}">{{ $v->registration }} · ไมล์ {{ $v->current_odometer }}</option>@endforeach</select><input type="date" name="trip_date" value="{{ now()->format('Y-m-d') }}" class="form-control mb-2" required><div class="row g-2"><div class="col"><input type="number" name="odometer_start" class="form-control" placeholder="ไมล์เริ่ม" required></div><div class="col"><input type="number" name="odometer_end" class="form-control" placeholder="ไมล์จบ" required></div></div><input name="route" class="form-control my-2" placeholder="เส้นทาง / งานที่ไป" required><div class="row g-2"><div class="col"><input name="fuel_liters" type="number" step="0.01" class="form-control" placeholder="น้ำมัน (ลิตร)"></div><div class="col"><input name="fuel_cost" type="number" step="0.01" class="form-control" placeholder="ค่าน้ำมัน"></div></div><button class="btn btn-success mt-2">บันทึกการวิ่ง</button></form></div></div></div>
<div class="col-lg-6"><div class="card"><div class="card-header">บันทึกซ่อม</div><div class="card-body"><form method="POST" action="{{ route('fleet.repairs.store') }}">@csrf<select name="vehicle_id" class="form-select mb-2" required><option value="">เลือกรถ</option>@foreach($vehicles as $v)<option value="{{ $v->id }}">{{ $v->registration }}</option>@endforeach</select><input type="date" name="repair_date" value="{{ now()->format('Y-m-d') }}" class="form-control mb-2" required><input type="number" name="odometer" class="form-control mb-2" placeholder="เลขไมล์ตอนซ่อม" required><input name="summary" class="form-control mb-2" placeholder="รายการซ่อม" required><div class="row g-2"><div class="col"><input name="vendor" class="form-control" placeholder="อู่ / ผู้ให้บริการ"></div><div class="col"><input name="cost" type="number" step="0.01" class="form-control" placeholder="ค่าใช้จ่าย"></div></div><button class="btn btn-warning mt-2">บันทึกประวัติซ่อม</button></form></div></div></div>
</div>
@endsection
