@extends('layout')
@section('title','รายงานรถ')
@section('page-title','รายงานรถและค่าใช้จ่าย')
@section('page-subtitle','สรุปการวิ่ง น้ำมัน และซ่อมบำรุงตามช่วงเวลา')
@section('content')
<div class="card mb-3"><div class="card-body"><form class="row g-2 align-items-end"><div class="col-md-3"><label class="form-label">ตั้งแต่</label><input class="form-control" type="date" name="from" value="{{ $from->toDateString() }}"></div><div class="col-md-3"><label class="form-label">ถึง</label><input class="form-control" type="date" name="to" value="{{ $to->toDateString() }}"></div><div class="col-md-3"><label class="form-label">รถ</label><select class="form-select" name="vehicle_id"><option value="">รถทั้งหมด</option>@foreach($vehicles as $v)<option value="{{ $v->id }}">{{ $v->registration }}</option>@endforeach</select></div><div class="col-md-3"><button class="btn btn-primary w-100">ค้นหารายงาน</button></div></form></div></div>
<div class="row g-3 mb-3"><div class="col-md-3"><div class="card"><div class="card-body"><small class="text-muted">ระยะทางรวม</small><h3>{{ number_format($summary['distance']) }} กม.</h3></div></div></div><div class="col-md-3"><div class="card"><div class="card-body"><small class="text-muted">น้ำมันรวม</small><h3>{{ number_format($summary['fuel_liters'],2) }} ลิตร</h3></div></div></div><div class="col-md-3"><div class="card"><div class="card-body"><small class="text-muted">ค่าน้ำมัน</small><h3>฿{{ number_format($summary['fuel_cost'],2) }}</h3></div></div></div><div class="col-md-3"><div class="card"><div class="card-body"><small class="text-muted">ค่าซ่อม</small><h3>฿{{ number_format($summary['repair_cost'],2) }}</h3></div></div></div></div>
<div class="card"><div class="card-header">สรุปแยกรถ</div><div class="table-responsive"><table class="table align-middle mb-0"><thead><tr><th>รถ</th><th>เลขไมล์ปัจจุบัน</th><th>ระยะทาง</th><th>น้ำมัน</th><th>ค่าน้ำมัน</th><th>ค่าซ่อม</th><th>ค่าใช้จ่าย/กม.</th></tr></thead><tbody>@forelse($vehicles as $v)@php($distance=$v->trips->sum(fn($t)=>$t->odometer_end-$t->odometer_start))@php($fuelCost=$v->trips->sum('fuel_cost'))@php($repairCost=$v->repairs->sum('cost'))<tr><td><strong>{{ $v->registration }}</strong><br><small class="text-muted">{{ $v->code }} · {{ $v->branch?->name_th ?? '-' }}</small></td><td>{{ number_format($v->current_odometer) }}</td><td>{{ number_format($distance) }} กม.</td><td>{{ number_format($v->trips->sum('fuel_liters'),2) }} ลิตร</td><td>฿{{ number_format($fuelCost,2) }}</td><td>฿{{ number_format($repairCost,2) }}</td><td>฿{{ number_format($distance>0?($fuelCost+$repairCost)/$distance:0,2) }}</td></tr>@empty<tr><td colspan="7" class="text-center">ไม่พบข้อมูลในช่วงเวลานี้</td></tr>@endforelse</tbody></table></div></div>
<div class="mt-3"><a href="{{ route('fleet.index') }}">กลับหน้าจัดการรถ</a></div>
@endsection
