<!doctype html>
<html lang="th">
<head>
    <meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
    <title>สมาชิกของฉัน | Popstar</title>
    <script src="https://static.line-scdn.net/liff/edge/2/sdk.js"></script>
    <style>
      :root{font-family:ui-sans-serif,system-ui,-apple-system,sans-serif;color:#172033;background:#f4f8fb}*{box-sizing:border-box}body{margin:0;background:radial-gradient(circle at 12% 0,#dff7f4 0,transparent 35%),#f4f8fb}.shell{max-width:520px;margin:auto;min-height:100vh;padding:24px 16px 104px}.top{display:flex;justify-content:space-between;align-items:center;margin-bottom:20px}.brand{font-size:15px;font-weight:900;letter-spacing:.08em;color:#087f8c}.muted{color:#718096;font-size:13px}.logout{border:1px solid #dce6ee;background:#fff;border-radius:999px;padding:8px 14px;color:#718096;font-size:12px}.hero{position:relative;overflow:hidden;background:linear-gradient(135deg,#087f8c 0%,#1262a5 100%);color:#fff;border-radius:26px;padding:24px;box-shadow:0 18px 34px #1262a530}.hero:after{content:'✦';position:absolute;right:20px;top:12px;color:#ffffff40;font-size:76px;line-height:1}.hero h1{position:relative;z-index:1;font-size:25px;margin:9px 0 2px}.hero .muted{position:relative;z-index:1;color:#d8f5f3}.tier{position:relative;z-index:1;display:inline-block;background:#ffffff28;border:1px solid #ffffff35;border-radius:99px;padding:6px 12px;font-size:12px}.points{position:relative;z-index:1;font-size:42px;line-height:1;font-weight:900;margin:28px 0 8px}.points small{font-size:14px;font-weight:700}.bar{height:9px;background:#ffffff40;border-radius:8px;overflow:hidden}.bar i{display:block;height:100%;width:72%;background:linear-gradient(90deg,#ffd166,#ffe59b);border-radius:8px}.grid{display:grid;grid-template-columns:repeat(2,1fr);gap:12px;margin-top:14px}.card{background:#fff;border:1px solid #e5edf2;border-radius:18px;padding:16px;min-height:96px;box-shadow:0 8px 22px #17324d0b}.card b{display:block;font-size:22px;margin-top:9px;color:#172033}.section{margin-top:24px}.section h2{font-size:18px;margin:0 0 11px}.activity{display:flex;align-items:center;gap:12px;min-height:76px;margin:9px 0!important}.activity-icon{display:grid;place-items:center;width:38px;height:38px;border-radius:12px;background:#e9f8f6;font-size:18px}.empty{color:#718096;font-size:13px}.nav{position:fixed;z-index:5;bottom:0;left:50%;transform:translateX(-50%);max-width:520px;width:100%;background:#fffffff2;backdrop-filter:blur(14px);border-top:1px solid #dfe9ef;display:flex;justify-content:space-around;padding:10px 8px calc(10px + env(safe-area-inset-bottom));box-shadow:0 -8px 24px #17324d0a}.nav button{border:0;background:transparent;color:#718096;font-size:12px;line-height:1.45;padding:4px 12px;border-radius:12px}.nav button.active{color:#087f8c;font-weight:800;background:#e9f8f6}.loading{text-align:center;padding:70px 20px;color:#718096}.error{background:#fff0f0;color:#a33;padding:16px;border-radius:16px;border:1px solid #ffd5d5}@media(max-width:360px){.shell{padding-left:12px;padding-right:12px}.hero{padding:20px}.points{font-size:36px}}
    </style>
</head>
<body><main class="shell">
  <div class="top"><div><div class="brand">POPSTAR MEMBER</div><div class="muted">สิทธิประโยชน์ของคุณ</div></div><button class="logout" id="logout">ออก</button></div>
  <div id="app" class="loading">กำลังตรวจสอบสมาชิก...</div>
</main><nav class="nav"><button class="active">⭐<br>แต้ม</button><button>🎟️<br>คูปอง</button><button>🎁<br>รางวัล</button><button>🧾<br>ซื้อ</button></nav>
<script>
const LIFF_ID=@json($liffId); const app=document.querySelector('#app');
async function get(path){const r=await fetch('/api/member/me'+path,{headers:{Accept:'application/json'}});if(!r.ok)throw new Error('กรุณาเปิดหน้านี้จาก LINE OA');return r.json()}
async function boot(){try{
  if(LIFF_ID){await liff.init({liffId:LIFF_ID});if(!liff.isLoggedIn())return liff.login();const token=liff.getIDToken();const auth=await fetch('/api/member/auth/liff',{method:'POST',headers:{'Content-Type':'application/json','X-CSRF-TOKEN':document.querySelector('meta[name=csrf-token]')?.content||''},body:JSON.stringify({id_token:token})});if(!auth.ok)throw new Error((await auth.json()).message||'เข้าสู่ระบบสมาชิกไม่สำเร็จ')}
  const [{member},points,history,purchases]=await Promise.all([get(''),get('/points'),get('/point-history'),get('/purchases')]);
  app.className='';app.innerHTML=`<section class="hero"><span class="tier">${points.tier}</span><h1>${member.name}</h1><div class="muted">รหัสสมาชิก ${member.member_code}</div><div class="points">${points.points.toLocaleString()} <small>Points</small></div><div class="bar"><i></i></div></section><div class="grid"><div class="card">⭐ แต้ม<b>${points.points.toLocaleString()}</b><span class="muted">แต้มคงเหลือ</span></div><div class="card">🧾 ซื้อ<b>${purchases.items.length}</b><span class="muted">รายการล่าสุด</span></div></div><section class="section"><h2>กิจกรรมแต้มล่าสุด</h2>${history.items.length?history.items.slice(0,5).map(x=>`<div class="card activity"><span class="activity-icon">${x.direction==='earn'?'＋':'－'}</span><div><b style="font-size:15px;margin:0">${x.direction==='earn'?'+':'-'}${x.points.toLocaleString()} แต้ม</b><span class="muted">${x.note||'รายการแต้ม'} · ${new Date(x.created_at).toLocaleDateString('th-TH')}</span></div></div>`).join(''):'<div class="card empty">ยังไม่มีรายการแต้ม</div>'}</section>`;
}catch(e){app.innerHTML=`<div class="error">${e.message}</div>`}}
document.querySelector('#logout').onclick=async()=>{await fetch('/api/member/logout',{method:'POST'});location.reload()};boot();
</script></body></html>
